const PAGE_CODES = {
  TRANG_CHU: 'TRANG_CHU',
  GIOI_THIEU: 'GIOI_THIEU',
  KHOA_HOC: 'KHOA_HOC',
  KIEN_THUC_CO: 'KIEN_THUC_CO',
  TIN_TUC: 'TIN_TUC',
  TUYEN_DUNG: 'TUYEN_DUNG',
  CHESS_SHOP: 'CHESS_SHOP',
  CHINH_SACH_BAO_MAT: 'CHINH_SACH_BAO_MAT',
  DIEU_KHOAN_SU_DUNG: 'DIEU_KHOAN_SU_DUNG'
}

export default PAGE_CODES
