export { default as Banner } from './Banner'
export { default as GeneralIntroduction } from './GeneralIntroduction'
export { default as TreeDiagram } from './TreeDiagram'
export { default as FirstInformation } from './FirstInformation'
export { default as SecondInformation } from './SecondInformation'
export { default as ChessNews } from './ChessNews'
export { default as ActivityNews } from './ActivityNews'
